/* Generated by Edit Mode - 2026-07-28T20:04:43.670Z */
window.CONTENT_DATA = {
  "version": 1,
  "projects": [
    {
      "id": "oapak",
      "title": "Once a Pawn a King",
      "desc": "<p>A chess-based turn-based roguelike and my main project for two years. <br>I formed and led the team as lead / producer, and owned character models, environments, animations, VFX and UI in Unity.</p>",
      "sections": [
        {
          "id": "oapak-characters",
          "title": "3D Characters",
          "desc": "<p>Pieces, bosses and mini-bosses - modeled in Maya, hand-textured in Procreate, outlined in Unity.</p>",
          "items": [
            {
              "id": "oapak-pieces",
              "type": "video",
              "src": "media/once-a-pawn-a-king/3d-characters/pieces_turns.mp4",
              "desc": "<p>Standard piece turnarounds.</p>",
              "software": [
                "maya",
                "unity",
                "procreate"
              ]
            },
            {
              "id": "oapak-unique-pieces",
              "type": "video",
              "src": "media/once-a-pawn-a-king/3d-characters/unique_pieces_turns.mp4",
              "desc": "<p>Hero piece turnarounds.</p>",
              "software": [
                "maya",
                "unity",
                "procreate"
              ]
            },
            {
              "id": "oapak-boss1",
              "type": "video",
              "src": "media/once-a-pawn-a-king/3d-characters/boss001.mp4",
              "desc": "<p>Pawnathan - boss turnaround</p>",
              "software": [
                "maya",
                "unity",
                "procreate"
              ]
            },
            {
              "id": "oapak-boss2",
              "type": "video",
              "src": "media/once-a-pawn-a-king/3d-characters/boss002.mp4",
              "desc": "<p>Bishoper - boss turnaround</p>",
              "software": [
                "maya",
                "unity",
                "procreate"
              ]
            },
            {
              "id": "oapak-cav1",
              "type": "video",
              "src": "media/once-a-pawn-a-king/3d-characters/cav001.mp4",
              "desc": "<p>Cavalier mini-boss turnaround</p>",
              "software": [
                "maya",
                "unity",
                "procreate"
              ]
            },
            {
              "id": "oapak-cav2",
              "type": "video",
              "src": "media/once-a-pawn-a-king/3d-characters/cav002.mp4",
              "desc": "<p>Cavalier mini-boss turnaround</p>",
              "software": [
                "maya",
                "unity",
                "procreate"
              ]
            }
          ]
        },
        {
          "id": "oapak-animations",
          "title": "Animations",
          "desc": "<p>Gameplay animation in Unity's Animator with blend shapes for organic motion. <br>Also animated the hero title cards and cut the release trailer.</p>",
          "items": [
            {
              "id": "oapak-pawnjamin-card",
              "type": "video",
              "src": "media/once-a-pawn-a-king/animations/pawnjamin_titlecard_compressed.mp4",
              "poster": "media/site/thumbnails/pawnjamin.webp",
              "desc": "<p>Pawnjamin title card.</p>",
              "software": [
                "unity",
                "davinci"
              ]
            },
            {
              "id": "oapak-pawnelope-card",
              "type": "video",
              "src": "media/once-a-pawn-a-king/animations/pawnelope_titlecard_compressed2.mp4",
              "poster": "media/site/thumbnails/pawnelope.webp",
              "desc": "<p>Pawnelope title card.</p>",
              "software": [
                "unity",
                "davinci"
              ]
            },
            {
              "id": "oapak-nathaniel-card",
              "type": "video",
              "src": "media/once-a-pawn-a-king/animations/nathaniel_card_01_comp.mp4",
              "poster": "media/site/thumbnails/nathaniel.webp",
              "desc": "<p>Nathaniel title card.</p>",
              "software": [
                "unity",
                "davinci"
              ]
            },
            {
              "id": "oapak-trailer",
              "type": "video",
              "src": "media/once-a-pawn-a-king/animations/oapak_trailer.mp4",
              "poster": "media/site/thumbnails/trailer.webp",
              "desc": "<p>Release trailer.</p>",
              "software": [
                "davinci"
              ]
            },
            {
              "id": "oapak-pieces-anims",
              "type": "video",
              "src": "media/once-a-pawn-a-king/animations/pieces_animations.mp4",
              "desc": "<p>Standard pieces - move, attack, capture.</p>",
              "software": [
                "unity"
              ]
            },
            {
              "id": "oapak-boss-anims",
              "type": "video",
              "src": "media/once-a-pawn-a-king/animations/boss_animations.mp4",
              "desc": "<p>Boss set - attacks, idles, reactions. Unity + blend shapes.</p>",
              "software": [
                "unity",
                "maya"
              ]
            }
          ]
        },
        {
          "id": "oapak-vfx",
          "title": "VFX",
          "desc": "<p>Real-time VFX in Unity Shader Graph and Particle Systems.</p>",
          "items": [
            {
              "id": "oapak-vfx2",
              "type": "video",
              "src": "media/once-a-pawn-a-king/vfxs-vids/vfx_002.mp4",
              "desc": "Mesh + particle effects for a more physical feel.",
              "software": [
                "unity"
              ]
            },
            {
              "id": "oapak-vfx1",
              "type": "video",
              "src": "media/once-a-pawn-a-king/vfxs-vids/vfx_001.mp4",
              "desc": "\"Cool guys don't look at EXPLOSIONS\"",
              "software": [
                "unity"
              ]
            },
            {
              "id": "oapak-vfx3",
              "type": "video",
              "src": "media/once-a-pawn-a-king/vfxs-vids/vfx_003.mp4",
              "desc": "<p>Blessing and Curse effects.</p>",
              "software": [
                "unity"
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "arcadia",
      "title": "Arcadia Untitled AAA",
      "desc": "<p>My first industry role, on Arcadia Games' Israeli team for an unannounced AAA licensed-IP project. We catalogued and repaired the franchise's 3D asset library, then explored character concepts to help shape art direction for the U.S. team.</p>",
      "sections": [
        {
          "id": "arcadia-sulley",
          "title": "Character Concept",
          "desc": "<p>Character concept - model and sculpt rework, plus concept animations for movement and framing.</p>",
          "items": [
            {
              "id": "arcadia-sulley-cooking",
              "type": "video",
              "src": "media/arcadia-untitled-aaa/sulley-character/sulley_cooking_anim_04.mp4",
              "desc": "<p>Cooking loop.</p>",
              "software": [
                "maya"
              ]
            },
            {
              "id": "arcadia-sulley-fishing",
              "type": "video",
              "src": "media/arcadia-untitled-aaa/sulley-character/sulley_fishing_loops_02.mp4",
              "desc": "<p>Fishing loops.</p>",
              "software": [
                "maya"
              ]
            },
            {
              "id": "arcadia-sulley-retopo",
              "type": "image",
              "src": "media/arcadia-untitled-aaa/sulley-character/sp_retopo_01.webp",
              "desc": "<p>High-detail sculpt.</p>",
              "software": [
                "zbrush"
              ]
            },
            {
              "id": "arcadia-sulley-wf",
              "type": "image",
              "src": "media/arcadia-untitled-aaa/sulley-character/wf_low_01.webp",
              "desc": "<p>Low-poly wireframe.</p>",
              "software": [
                "maya"
              ]
            }
          ]
        },
        {
          "id": "arcadia-balloon",
          "title": "Balloon Cart",
          "desc": "<p>Stylized balloon cart prop - modeled, textured, turntable render.</p>",
          "items": [
            {
              "id": "arcadia-balloon1",
              "type": "video",
              "src": "media/arcadia-untitled-aaa/baloon-cart/balloon_cart_render_01.mp4",
              "desc": "<p>Full turntable with materials and lighting.</p>",
              "software": [
                "maya",
                "substance"
              ]
            },
            {
              "id": "arcadia-balloon2",
              "type": "video",
              "src": "media/arcadia-untitled-aaa/baloon-cart/balloon_cart_render_02.mp4",
              "desc": "<p>Close-up material and texture pass.</p>",
              "software": [
                "maya",
                "substance"
              ]
            }
          ]
        },
        {
          "id": "arcadia-wagon",
          "title": "Wagon",
          "desc": "<p>Wooden wagon prop - beauty renders, wireframe and normal-map breakdown.</p>",
          "items": [
            {
              "id": "arcadia-wagon1",
              "type": "image",
              "src": "media/arcadia-untitled-aaa/wagon/001.webp",
              "desc": "<p>Beauty render.</p>",
              "software": [
                "maya",
                "substance"
              ]
            },
            {
              "id": "arcadia-wagon-wf",
              "type": "image",
              "src": "media/arcadia-untitled-aaa/wagon/001_wf.webp",
              "desc": "<p>Wireframe / topology.</p>",
              "software": [
                "maya"
              ]
            },
            {
              "id": "arcadia-wagon-nm",
              "type": "image",
              "src": "media/arcadia-untitled-aaa/wagon/001_nm.webp",
              "desc": "<p>Normal-map bake from the high-poly.</p>",
              "software": [
                "maya",
                "substance"
              ]
            },
            {
              "id": "arcadia-wagon2",
              "type": "image",
              "src": "media/arcadia-untitled-aaa/wagon/002.webp",
              "desc": "<p>Alternate angle.</p>",
              "software": [
                "maya",
                "substance"
              ]
            },
            {
              "id": "arcadia-wagon3",
              "type": "image",
              "src": "media/arcadia-untitled-aaa/wagon/003.webp",
              "desc": "<p>Alternate angle.</p>",
              "software": [
                "maya",
                "substance"
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "other",
      "title": "Simulators & Other",
      "desc": "<p>Client and studio work at Clover Bite - 3D models, terrain, environment assets, UI and tech art in Maya and Unity.</p>",
      "sections": [
        {
          "id": "other-educoop",
          "title": "Educational COOP Game",
          "desc": "<p>A team-based educational game about cooperation. I built its eight island levels with Unity terrain tools - terraforming, level design and population - plus customizable characters, prizes and gameplay assets.</p>",
          "items": [
            {
              "id": "educoop-01",
              "type": "image",
              "src": "media/other-projects/educational-coop-game/001.webp",
              "desc": "<p>Island level - Unity terrain, dressing, population.</p>",
              "software": [
                "unity",
                "maya",
                "substance"
              ]
            },
            {
              "id": "educoop-02",
              "type": "image",
              "src": "media/other-projects/educational-coop-game/002.webp",
              "desc": "<p>Island level - Unity terrain, dressing, population.</p>",
              "software": [
                "unity",
                "maya",
                "substance"
              ]
            },
            {
              "id": "educoop-03",
              "type": "image",
              "src": "media/other-projects/educational-coop-game/003.webp",
              "desc": "<p>Island level - Unity terrain, dressing, population.</p>",
              "software": [
                "unity",
                "maya",
                "substance"
              ]
            },
            {
              "id": "educoop-04",
              "type": "image",
              "src": "media/other-projects/educational-coop-game/004.webp",
              "desc": "<p>Island level - Unity terrain, dressing, population.</p>",
              "software": [
                "unity",
                "maya",
                "substance"
              ]
            },
            {
              "id": "educoop-05",
              "type": "image",
              "src": "media/other-projects/educational-coop-game/005.webp",
              "desc": "<p>Island level - Unity terrain, dressing, population.</p>",
              "software": [
                "unity",
                "maya",
                "substance"
              ]
            },
            {
              "id": "educoop-06",
              "type": "image",
              "src": "media/other-projects/educational-coop-game/006.webp",
              "desc": "<p>Island level - Unity terrain, dressing, population.</p>",
              "software": [
                "unity",
                "maya",
                "substance"
              ]
            },
            {
              "id": "educoop-07",
              "type": "image",
              "src": "media/other-projects/educational-coop-game/007.webp",
              "desc": "<p>Island level - Unity terrain, dressing, population.</p>",
              "software": [
                "unity",
                "maya",
                "substance"
              ]
            },
            {
              "id": "educoop-08",
              "type": "image",
              "src": "media/other-projects/educational-coop-game/008.webp",
              "desc": "<p>Island level - Unity terrain, dressing, population.</p>",
              "software": [
                "unity",
                "maya",
                "substance"
              ]
            },
            {
              "id": "educoop-09",
              "type": "image",
              "src": "media/other-projects/educational-coop-game/009.webp",
              "desc": "<p>Island level - Unity terrain, dressing, population.</p>",
              "software": [
                "unity",
                "maya",
                "substance"
              ]
            },
            {
              "id": "educoop-10",
              "type": "image",
              "src": "media/other-projects/educational-coop-game/010.webp",
              "desc": "<p>Island level - Unity terrain, dressing, population.</p>",
              "software": [
                "unity",
                "maya",
                "substance"
              ]
            },
            {
              "id": "educoop-11",
              "type": "image",
              "src": "media/other-projects/educational-coop-game/011.webp",
              "desc": "<p>Island level - Unity terrain, dressing, population.</p>",
              "software": [
                "unity",
                "maya",
                "substance"
              ]
            },
            {
              "id": "educoop-12",
              "type": "image",
              "src": "media/other-projects/educational-coop-game/012.webp",
              "desc": "<p>Island level - Unity terrain, dressing, population.</p>",
              "software": [
                "unity",
                "maya",
                "substance"
              ]
            },
            {
              "id": "educoop-ld1",
              "type": "image",
              "src": "media/other-projects/educational-coop-game/ld_001.webp",
              "desc": "<p>Level design layout.</p>",
              "software": [
                "figma"
              ]
            },
            {
              "id": "educoop-ld2",
              "type": "image",
              "src": "media/other-projects/educational-coop-game/ld_002.webp",
              "desc": "<p>Level design layout.</p>",
              "software": [
                "figma"
              ]
            },
            {
              "id": "educoop-ld3",
              "type": "image",
              "src": "media/other-projects/educational-coop-game/ld_003.webp",
              "desc": "<p>Level design layout.</p>",
              "software": [
                "figma"
              ]
            }
          ]
        },
        {
          "id": "other-medsim",
          "title": "Medical Services Simulator",
          "desc": "<p>A training simulator for a national EMS, preparing crews for mass-casualty incidents. I modeled patients, medics, vehicles and city environments - apartments, a train station, hospitals - in Maya, Substance Painter and Photoshop, implemented in Unity.</p>",
          "items": [
            {
              "id": "medsim-amb-nav",
              "type": "video",
              "src": "media/other-projects/medical-services-simulator/ambulance_navigation.mp4",
              "desc": "<p>Gameplay footage.</p>",
              "software": [
                "unity"
              ]
            },
            {
              "id": "medsim-amb-siren",
              "type": "video",
              "src": "media/other-projects/medical-services-simulator/ambulance_siren.mp4",
              "desc": "<p>Gameplay footage.</p>",
              "software": [
                "unity"
              ]
            },
            {
              "id": "medsim-stretcher",
              "type": "video",
              "src": "media/other-projects/medical-services-simulator/patient-care-and-stretcher.mp4",
              "desc": "<p>Gameplay footage.</p>",
              "software": [
                "unity"
              ]
            },
            {
              "id": "medsim-01",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/01.webp",
              "desc": "<p>Simulator scene - environment and assets.</p>",
              "software": [
                "unity",
                "maya"
              ]
            },
            {
              "id": "medsim-001",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/001.webp",
              "desc": "<p>Simulator scene - environment and assets.</p>",
              "software": [
                "unity",
                "maya"
              ]
            },
            {
              "id": "medsim-002",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/002.webp",
              "desc": "<p>Simulator scene - environment and assets.</p>",
              "software": [
                "unity",
                "maya"
              ]
            },
            {
              "id": "medsim-bg",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/bg_b_002.webp",
              "desc": "<p>Simulator scene - environment and assets.</p>",
              "software": [
                "unity",
                "maya"
              ]
            },
            {
              "id": "medsim-f1825",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/f1825_001.webp",
              "desc": "<p>Patient character - modeled and textured.</p>",
              "software": [
                "maya",
                "substance"
              ]
            },
            {
              "id": "medsim-f6875",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/f6875_002.webp",
              "desc": "<p>Patient character - modeled and textured.</p>",
              "software": [
                "maya",
                "substance"
              ]
            },
            {
              "id": "medsim-k0810",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/k0810_001.webp",
              "desc": "<p>Patient character - modeled and textured.</p>",
              "software": [
                "maya",
                "substance"
              ]
            },
            {
              "id": "medsim-m6875",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/m6875_001.webp",
              "desc": "<p>Patient character - modeled and textured.</p>",
              "software": [
                "maya",
                "substance"
              ]
            },
            {
              "id": "medsim-ow1",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/ow_01.webp",
              "desc": "<p>Simulator scene - environment and assets.</p>",
              "software": [
                "unity",
                "maya"
              ]
            },
            {
              "id": "medsim-ow2",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/ow_02.webp",
              "desc": "<p>Simulator scene - environment and assets.</p>",
              "software": [
                "unity",
                "maya"
              ]
            },
            {
              "id": "medsim-p001",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/p001.webp",
              "desc": "<p>Simulator scene - environment and assets.</p>",
              "software": [
                "unity",
                "maya"
              ]
            },
            {
              "id": "medsim-ts",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/ts001.webp",
              "desc": "<p>Simulator scene - environment and assets.</p>",
              "software": [
                "unity",
                "maya"
              ]
            },
            {
              "id": "medsim-ppack2",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/med_pat_ppack_012.webp",
              "desc": "<p>Medical equipment props.</p>",
              "software": [
                "maya",
                "substance"
              ]
            },
            {
              "id": "medsim-ppack1",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/med_pat_ppack_01.webp",
              "desc": "<p>Medical equipment props.</p>",
              "software": [
                "maya",
                "substance"
              ]
            },
            {
              "id": "medsim-packs1",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/packs_001.webp",
              "desc": "<p>Medical equipment props.</p>",
              "software": [
                "maya"
              ]
            },
            {
              "id": "medsim-packs2",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/packs_002.webp",
              "desc": "<p>Medical equipment props.</p>",
              "software": [
                "maya"
              ]
            },
            {
              "id": "medsim-packs3",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/packs_003.webp",
              "desc": "<p>Medical equipment props.</p>",
              "software": [
                "maya",
                "substance"
              ]
            },
            {
              "id": "medsim-packs4",
              "type": "image",
              "src": "media/other-projects/medical-services-simulator/packs_004.webp",
              "desc": "<p>Medical equipment props.</p>",
              "software": [
                "maya",
                "substance"
              ]
            }
          ]
        },
        {
          "id": "other-ringmatch",
          "title": "RingMatch",
          "desc": "<p>Casual mobile puzzle prototype - 3D modeling, texturing and VFX in Unity, plus logo, UI assets and tutorial graphics.</p>",
          "items": [
            {
              "id": "ringmatch-video",
              "type": "video",
              "src": "media/other-projects/ringmatch/ringmatch_publishervideo.mp4",
              "desc": "<p>Publisher gameplay video.</p>",
              "software": [
                "unity",
                "davinci"
              ]
            },
            {
              "id": "ringmatch-logo",
              "type": "image",
              "src": "media/other-projects/ringmatch/logoblue_01.webp",
              "desc": "<p>Logo.</p>",
              "software": [
                "illustrator",
                "photoshop"
              ]
            },
            {
              "id": "ringmatch-ui2",
              "type": "image",
              "src": "media/other-projects/ringmatch/rincore_ui_assetspread_02.webp",
              "desc": "<p>UI asset spread.</p>",
              "software": [
                "illustrator",
                "figma"
              ]
            },
            {
              "id": "ringmatch-ui3",
              "type": "image",
              "src": "media/other-projects/ringmatch/rincore_ui_assetspread_03.webp",
              "desc": "<p>UI asset spread.</p>",
              "software": [
                "illustrator",
                "figma"
              ]
            },
            {
              "id": "ringmatch-tutorial",
              "type": "image",
              "src": "media/other-projects/ringmatch/tutorial-hand-frames_02.webp",
              "desc": "<p>Tutorial hand frames.</p>",
              "software": [
                "illustrator",
                "photoshop"
              ]
            }
          ]
        }
      ]
    }
  ],
  "site": {
    "portrait": {
      "x": -435,
      "y": -238,
      "h": 384
    },
    "bio1": "Started as a 3D artist at Clover Bite on client simulators and mobile prototypes -<div><b>modeling, terrain & environments, UVs, textures, VFX and animation.</b></div>",
    "bio2": "Then formed and led the team behind <i>Once a Pawn a King</i>,<br>our debut Steam title.",
    "bio3": "The studio has since closed -<br><b>I'm looking for my next place to make great games!</b>",
    "cvPortrait": {
      "top": 23,
      "right": 857,
      "h": 266
    }
  },
  "cv": {
    ".cv-entry-org#1": "\n                  <img class=\"cv-org-logo cv-org-logo--screen\" src=\"media/site/cloverbite_logo.webp\" alt=\"Clover Bite\" contenteditable=\"false\">\n                  Clover Bite&nbsp;",
    ".cv-entry-org#3": "\n                  <img class=\"cv-org-logo cv-org-logo--pill\" src=\"media/site/tiltan_logo.webp\" alt=\"Tiltan\" contenteditable=\"false\">\n                  Tiltan School of Design &amp; Visual Communication",
    ".cv-entry-desc#0": "Generalist 3D: modeling, UVs, texturing, rigging, animation, shaders, rendering &amp; lighting. Plus Unity and Unreal basics, 2D design, illustration, UI/UX and art theory.",
    ".cv-entry-bullets li#6": "Repaired and catalogued 3D assets from an archived licensed-IP project.",
    ".cv-entry-bullets li#7": "Character concept models exploring art direction for the U.S. team.",
    ".cv-entry-title#1": "3D Generalist",
    ".cv-entry-date#0": "Jun 2024 - Jun 2026",
    ".cv-entry-date#1": "Jul 2022 - May 2024",
    ".cv-entry-bullets li#3": "Character modeling and texturing (mostly human), environment assets, Unity terrains and level design.",
    ".cv-entry-bullets li#2": "Shipped Once a Pawn a King on Steam.",
    ".cv-entry-bullets li#1": "Ran indie production - development, promotional materials and publisher talks.",
    ".cv-entry-bullets li#0": "Formed and led the core team as lead / producer; owned 3D character art, environments, animation and VFX.",
    ".cv-section-label#4": "<font size=\"5\">Software</font>",
    ".cv-summary-text#0": "Game developer and 3D artist covering most of the production pipeline - character modeling, rigging, environment art, real-time VFX, shaders and UI/UX.<div>Studied 3D art and game design at Tiltan, then spent four years in its studio on commercial titles and client projects.</div>",
    ".cv-section-label#0": "<font size=\"5\">Summary</font>",
    ".cv-section-label#1": "<font size=\"5\">Skills</font>",
    ".cv-section-label#2": "<font size=\"5\">Experience</font>",
    ".cv-entry-bullets li#8": "Asset-library organization and production tracking.",
    ".cv-entry-bullets li#5": "UI for both, from design to in-engine implementation.",
    ".cv-entry-bullets li#4": "Two client projects: a national EMS training simulator and an educational co-op game.",
    ".cv-subtitle-sub#0": "<b>3D ART &nbsp;|&nbsp; TECH ART &nbsp;|&nbsp; ANIMATION</b>",
    ".cv-subtitle-main#0": "UNITY GAME ARTIST"
  }
};
